import os

APPWRITE_ENDPOINT = os.getenv("APPWRITE_ENDPOINT")
APPWRITE_PROJECT = os.getenv("APPWRITE_PROJECT")
APPWRITE_API_KEY = os.getenv("APPWRITE_API_KEY")
APPWRITE_DB = os.getenv("APPWRITE_DB")
APPWRITE_COLLECTION = os.getenv("APPWRITE_COLLECTION")
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
